openapi: 3.2.0
info:
  title: JobBOSS² Public Releases API
  description: Provides a common API surface for accessing ECI ERP JobBOSS².
  version: v1
servers:
- url: https://api-jb2.integrations.ecimanufacturing.com:443
  description: API Host
security:
- Bearer: []
tags:
- name: Releases
paths:
  /api/v1/orders/{orderNumber}/order-line-items/{itemNumber}/releases:
    post:
      tags:
      - Releases
      summary: Creates a Order Release
      parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
      - name: itemNumber
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReleaseCreate'
            example:
              binLocation: string
              comments: string
              deliveryType: 0
              dueDate: '2026-09-06T17:13:12.0000000+00:00'
              EDISoftItemNumber: 0
              lastModDate: '2026-09-06T17:13:12.0000000+00:00'
              lastModUser: string
              lotNumber: string
              quantity: 0
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
              example:
                binLocation: string
                comments: string
                dateComplete: '2026-09-06T17:13:12.0000000+00:00'
                deliveryTicketNumber: string
                deliveryType: 0
                destinationJobNumber: string
                dueDate: '2026-09-06T17:13:12.0000000+00:00'
                EDISoftItemNumber: 0
                itemNumber: 0
                jobNumber: string
                lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                lastModUser: string
                lotNumber: string
                manufacturingJobNumber: string
                orderNumber: string
                partDescription: string
                partNumber: string
                quantity: 0
                uniqueID: 0
      operationId: postApiV1OrdersByOrderNumberOrderLineItemsByItemNumberReleases
      x-operation-id-source: derived
  /api/v1/orders/{orderNumber}/order-line-items/{itemNumber}/releases/{uniqueID}:
    get:
      tags:
      - Releases
      summary: Gets an Order Release from an order by Order Number, Item Number and Unique ID
      description: 'By default a release response will include only the fields: binLocation, comments, dateComplete, deliveryTicketNumber, deliveryType, destinationJobNumber, dueDate, itemNumber, jobNumber, lastModDate, lotNumber, manufacturingJobNumber, orderNumber, partDescription, partNumber, quantity, uniqueID. You may specify the exact fields to return using the fields parameter.'
      parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
      - name: itemNumber
        in: path
        required: true
        schema:
          type: string
      - name: uniqueID
        in: path
        required: true
        schema:
          type: string
      - name: fields
        in: query
        description: A comma separated list of fields to include in the result.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReleaseSuccessResponse'
              example:
                Data:
                  binLocation: string
                  comments: string
                  dateComplete: '2026-09-06T17:13:12.0000000+00:00'
                  deliveryTicketNumber: string
                  deliveryType: 0
                  destinationJobNumber: string
                  dueDate: '2026-09-06T17:13:12.0000000+00:00'
                  EDISoftItemNumber: 0
                  itemNumber: 0
                  jobNumber: string
                  lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                  lastModUser: string
                  lotNumber: string
                  manufacturingJobNumber: string
                  orderNumber: string
                  partDescription: string
                  partNumber: string
                  quantity: 0
                  uniqueID: 0
      operationId: getApiV1OrdersByOrderNumberOrderLineItemsByItemNumberReleasesByUniqueID
      x-operation-id-source: derived
  /api/v1/releases:
    get:
      tags:
      - Releases
      summary: Gets a list of Releases
      description: 'By default a release response will include only the fields: binLocation, comments, dateComplete, deliveryTicketNumber, deliveryType, destinationJobNumber, dueDate, itemNumber, jobNumber, lastModDate, lotNumber, manufacturingJobNumber, orderNumber, partDescription, partNumber, quantity, uniqueID. You may specify the exact fields to return using the fields parameter.'
      parameters:
      - name: fields
        in: query
        description: A comma separated list of fields to include in the result.
        schema:
          type: string
      - name: sort
        in: query
        description: A comma separated list of field to sort by. See the <a href='#sort-expressions'>Sort Expressions</a> section for more information.
        schema:
          type: string
      - name: filters
        in: query
        description: Filters must be provided as query string parameters as defined in the <a href='#filter-expressions'>Filter Expressions</a> section.
        schema:
          type: object
          additionalProperties:
            type: string
        examples:
          No filters: {}
          Filter by Order:
            value:
              orderNumber: '7025'
      - name: skip
        in: query
        description: The number of records at the start of the result set to skip over.
        schema:
          type: string
      - name: take
        in: query
        description: The number of records to retrieve.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReleaseListSuccessResponse'
              example:
                Data:
                - binLocation: string
                  comments: string
                  dateComplete: '2026-09-06T17:13:12.0000000+00:00'
                  deliveryTicketNumber: string
                  deliveryType: 0
                  destinationJobNumber: string
                  dueDate: '2026-09-06T17:13:12.0000000+00:00'
                  EDISoftItemNumber: 0
                  itemNumber: 0
                  jobNumber: string
                  lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                  lastModUser: string
                  lotNumber: string
                  manufacturingJobNumber: string
                  orderNumber: string
                  partDescription: string
                  partNumber: string
                  quantity: 0
                  uniqueID: 0
      operationId: getApiV1Releases
      x-operation-id-source: derived
components:
  schemas:
    ReleaseListSuccessResponse:
      type: object
      properties:
        Data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Release'
      additionalProperties: false
    Release:
      type: object
      properties:
        binLocation:
          type:
          - string
          - 'null'
          readOnly: true
        comments:
          type:
          - string
          - 'null'
          readOnly: true
        dateComplete:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        deliveryTicketNumber:
          type:
          - string
          - 'null'
          readOnly: true
        deliveryType:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        destinationJobNumber:
          type:
          - string
          - 'null'
          readOnly: true
        dueDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        EDISoftItemNumber:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        itemNumber:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        jobNumber:
          type:
          - string
          - 'null'
          readOnly: true
        lastModDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        lastModUser:
          type:
          - string
          - 'null'
          readOnly: true
        lotNumber:
          type:
          - string
          - 'null'
          readOnly: true
        manufacturingJobNumber:
          type:
          - string
          - 'null'
          readOnly: true
        orderNumber:
          type:
          - string
          - 'null'
          readOnly: true
        partDescription:
          type:
          - string
          - 'null'
          readOnly: true
        partNumber:
          type:
          - string
          - 'null'
          readOnly: true
        quantity:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        uniqueID:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
    ReleaseSuccessResponse:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/Release'
      additionalProperties: false
    ReleaseCreate:
      required:
      - quantity
      type: object
      properties:
        binLocation:
          type:
          - string
          - 'null'
        comments:
          type:
          - string
          - 'null'
        deliveryType:
          type:
          - integer
          - 'null'
          format: int32
        dueDate:
          type:
          - string
          - 'null'
          format: date-time
        EDISoftItemNumber:
          type:
          - integer
          - 'null'
          format: int32
        lastModDate:
          type:
          - string
          - 'null'
          format: date-time
        lastModUser:
          type:
          - string
          - 'null'
        lotNumber:
          type:
          - string
          - 'null'
        quantity:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: oauth2
      description: OAuth 2.0 Client Credentials Flow with API Users issued from Integration Engine Management Console
      flows:
        clientCredentials:
          tokenUrl: https://api-user.integrations.ecimanufacturing.com/oauth2/api-user/token
          scopes:
            openid: openid
