openapi: 3.2.0
info:
  title: JobBOSS² Public Order Routings API
  description: Provides a common API surface for accessing ECI ERP JobBOSS².
  version: v1
servers:
- url: https://api-jb2.integrations.ecimanufacturing.com:443
  description: API Host
security:
- Bearer: []
tags:
- name: Order Routings
paths:
  /api/v1/order-routings:
    get:
      tags:
      - Order Routings
      summary: Gets a list of Order Routings
      description: 'By default an order routing response will include only the fields: actualEndDate, actualPiecesGood, actualPiecesScrap, actualStartDate, burdenRate, departmentNumber, description, employeeCode, estimatedEndDate, estimatedQuantity, estimatedStartDate, itemNumber, jobNumber, laborRate, lastModDate, leadTime, machinesRun, numberMachinesForJob, operationCode, orderNumber, partNumber, shift2DefaultEmployeeCode, shift3DefaultEmployeeCode, status, stepNumber, timeUnit, total, totalActualHours, totalEstimatedHours, totalHoursLeft, uniqueID, vendorCode, workCenter, workCenterOrVendor. You may specify the exact fields to return using the fields parameter.'
      parameters:
      - name: fields
        in: query
        description: A comma separated list of fields to include in the result.
        schema:
          type: string
      - name: sort
        in: query
        description: A comma separated list of field to sort by. See the <a href='#sort-expressions'>Sort Expressions</a> section for more information.
        schema:
          type: string
      - name: filters
        in: query
        description: Filters must be provided as query string parameters as defined in the <a href='#filter-expressions'>Filter Expressions</a> section.
        schema:
          type: object
          additionalProperties:
            type: string
        examples:
          No filters: {}
          Filter by Order:
            value:
              orderNumber: '7025'
      - name: skip
        in: query
        description: The number of records at the start of the result set to skip over.
        schema:
          type: string
      - name: take
        in: query
        description: The number of records to retrieve.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRoutingListSuccessResponse'
              example:
                Data:
                - actualEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  actualPiecesGood: 0
                  actualPiecesScrap: 0
                  actualStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  burdenRate: 0
                  certificationRequired: false
                  cost1: 0
                  cost2: 0
                  cost3: 0
                  cost4: 0
                  cost5: 0
                  cost6: 0
                  cost7: 0
                  cost8: 0
                  cyclePrice: 0
                  cycleRate: 0
                  cycleTime: 0
                  cycleUnit: string
                  departmentNumber: string
                  description: string
                  employeeCode: string
                  estimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  estimatedQuantity: 0
                  estimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  GLCode: string
                  ignoreVendorMinimum: false
                  itemNumber: 0
                  jobClosedDate: '2026-09-06T17:13:12.0000000+00:00'
                  jobStatus: string
                  jobNumber: string
                  laborAccount: string
                  laborRate: 0
                  lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                  lastModUser: string
                  leadTime: 0
                  machinesRun: 0
                  markupPercent: 0
                  numberMachinesForJob: 0
                  operationCode: string
                  orderNumber: string
                  overlapSteps: false
                  partNumber: string
                  percentEfficient: 0
                  scrapPercent: 0
                  setup1: 0
                  setup2: 0
                  setup3: 0
                  setup4: 0
                  setup5: 0
                  setup6: 0
                  setup7: 0
                  setup8: 0
                  setupPrice: 0
                  setupRate: 0
                  setupTime: 0
                  shift2DefaultEmployeeCode: string
                  shift3DefaultEmployeeCode: string
                  status: string
                  stepNumber: 0
                  teamSize: 0
                  tempEstimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  tempEstimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  timeUnit: string
                  total: 0
                  totalActualHours: 0
                  totalEstimatedHours: 0
                  totalHoursLeft: 0
                  unattendedOperation: false
                  uniqueID: 0
                  unit1: string
                  unit2: string
                  unit3: string
                  unit4: string
                  unit5: string
                  unit6: string
                  unit7: string
                  unit8: string
                  vendorCode: string
                  workCenter: string
                  workCenterOrVendor: string
      operationId: getApiV1OrderRoutings
      x-operation-id-source: derived
  /api/v1/orders/{orderNumber}/order-line-items/{itemNumber}/order-routings:
    post:
      tags:
      - Order Routings
      summary: Creates an Order Routing
      parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
      - name: itemNumber
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRoutingCreate'
            example:
              certificationRequired: false
              cyclePrice: 0
              cycleTime: 0
              cycleUnit: string
              departmentNumber: string
              description: string
              employeeCode: string
              estimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
              estimatedQuantity: 0
              estimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
              ignoreVendorMinimum: false
              operationCode: string
              overlapSteps: false
              setupPrice: 0
              setupTime: 0
              shift2DefaultEmployeeCode: string
              shift3DefaultEmployeeCode: string
              stepNumber: 0
              timeUnit: string
              total: 0
              vendorCode: string
              workCenter: string
              workCenterOrVendor: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRouting'
              example:
                actualEndDate: '2026-09-06T17:13:12.0000000+00:00'
                actualPiecesGood: 0
                actualPiecesScrap: 0
                actualStartDate: '2026-09-06T17:13:12.0000000+00:00'
                burdenRate: 0
                certificationRequired: false
                cost1: 0
                cost2: 0
                cost3: 0
                cost4: 0
                cost5: 0
                cost6: 0
                cost7: 0
                cost8: 0
                cyclePrice: 0
                cycleRate: 0
                cycleTime: 0
                cycleUnit: string
                departmentNumber: string
                description: string
                employeeCode: string
                estimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                estimatedQuantity: 0
                estimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                GLCode: string
                ignoreVendorMinimum: false
                itemNumber: 0
                jobClosedDate: '2026-09-06T17:13:12.0000000+00:00'
                jobStatus: string
                jobNumber: string
                laborAccount: string
                laborRate: 0
                lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                lastModUser: string
                leadTime: 0
                machinesRun: 0
                markupPercent: 0
                numberMachinesForJob: 0
                operationCode: string
                orderNumber: string
                overlapSteps: false
                partNumber: string
                percentEfficient: 0
                scrapPercent: 0
                setup1: 0
                setup2: 0
                setup3: 0
                setup4: 0
                setup5: 0
                setup6: 0
                setup7: 0
                setup8: 0
                setupPrice: 0
                setupRate: 0
                setupTime: 0
                shift2DefaultEmployeeCode: string
                shift3DefaultEmployeeCode: string
                status: string
                stepNumber: 0
                teamSize: 0
                tempEstimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                tempEstimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                timeUnit: string
                total: 0
                totalActualHours: 0
                totalEstimatedHours: 0
                totalHoursLeft: 0
                unattendedOperation: false
                uniqueID: 0
                unit1: string
                unit2: string
                unit3: string
                unit4: string
                unit5: string
                unit6: string
                unit7: string
                unit8: string
                vendorCode: string
                workCenter: string
                workCenterOrVendor: string
      operationId: postApiV1OrdersByOrderNumberOrderLineItemsByItemNumberOrderRoutings
      x-operation-id-source: derived
  /api/v1/orders/{orderNumber}/order-line-items/{itemNumber}/order-routings/{stepNumber}:
    get:
      tags:
      - Order Routings
      summary: Gets an order routing by order number and order routing's item number and order…
      description: 'By default an order routing response will include only the fields: actualEndDate, actualPiecesGood, actualPiecesScrap, actualStartDate, burdenRate, departmentNumber, description, employeeCode, estimatedEndDate, estimatedQuantity, estimatedStartDate, itemNumber, jobNumber, laborRate, lastModDate, leadTime, machinesRun, numberMachinesForJob, operationCode, orderNumber, partNumber, shift2DefaultEmployeeCode, shift3DefaultEmployeeCode, status, stepNumber, timeUnit, total, totalActualHours, totalEstimatedHours, totalHoursLeft, uniqueID, vendorCode, workCenter, workCenterOrVendor. You may specify the exact fields to return using the fields parameter.'
      parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
      - name: itemNumber
        in: path
        required: true
        schema:
          type: string
      - name: stepNumber
        in: path
        required: true
        schema:
          type: string
      - name: fields
        in: query
        description: A comma separated list of fields to include in the result.
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRoutingSuccessResponse'
              example:
                Data:
                  actualEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  actualPiecesGood: 0
                  actualPiecesScrap: 0
                  actualStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  burdenRate: 0
                  certificationRequired: false
                  cost1: 0
                  cost2: 0
                  cost3: 0
                  cost4: 0
                  cost5: 0
                  cost6: 0
                  cost7: 0
                  cost8: 0
                  cyclePrice: 0
                  cycleRate: 0
                  cycleTime: 0
                  cycleUnit: string
                  departmentNumber: string
                  description: string
                  employeeCode: string
                  estimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  estimatedQuantity: 0
                  estimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  GLCode: string
                  ignoreVendorMinimum: false
                  itemNumber: 0
                  jobClosedDate: '2026-09-06T17:13:12.0000000+00:00'
                  jobStatus: string
                  jobNumber: string
                  laborAccount: string
                  laborRate: 0
                  lastModDate: '2026-09-06T17:13:12.0000000+00:00'
                  lastModUser: string
                  leadTime: 0
                  machinesRun: 0
                  markupPercent: 0
                  numberMachinesForJob: 0
                  operationCode: string
                  orderNumber: string
                  overlapSteps: false
                  partNumber: string
                  percentEfficient: 0
                  scrapPercent: 0
                  setup1: 0
                  setup2: 0
                  setup3: 0
                  setup4: 0
                  setup5: 0
                  setup6: 0
                  setup7: 0
                  setup8: 0
                  setupPrice: 0
                  setupRate: 0
                  setupTime: 0
                  shift2DefaultEmployeeCode: string
                  shift3DefaultEmployeeCode: string
                  status: string
                  stepNumber: 0
                  teamSize: 0
                  tempEstimatedEndDate: '2026-09-06T17:13:12.0000000+00:00'
                  tempEstimatedStartDate: '2026-09-06T17:13:12.0000000+00:00'
                  timeUnit: string
                  total: 0
                  totalActualHours: 0
                  totalEstimatedHours: 0
                  totalHoursLeft: 0
                  unattendedOperation: false
                  uniqueID: 0
                  unit1: string
                  unit2: string
                  unit3: string
                  unit4: string
                  unit5: string
                  unit6: string
                  unit7: string
                  unit8: string
                  vendorCode: string
                  workCenter: string
                  workCenterOrVendor: string
      operationId: getApiV1OrdersByOrderNumberOrderLineItemsByItemNumberOrderRoutingsByStepNumber
      x-operation-id-source: derived
    patch:
      tags:
      - Order Routings
      summary: Updates an Order Routing
      parameters:
      - name: orderNumber
        in: path
        required: true
        schema:
          type: string
      - name: itemNumber
        in: path
        required: true
        schema:
          type: string
      - name: stepNumber
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRoutingUpdate'
            example:
              operationCode: string
              employeeCode: string
              estimatedEndDate: '2026-09-06T17:13:12.8259325+00:00'
              estimatedStartDate: '2026-09-06T17:13:12.8259334+00:00'
              workCenter: string
      responses:
        '204':
          description: Success
      operationId: patchApiV1OrdersByOrderNumberOrderLineItemsByItemNumberOrderRoutingsByStepNumber
      x-operation-id-source: derived
components:
  schemas:
    OrderRoutingListSuccessResponse:
      type: object
      properties:
        Data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OrderRouting'
      additionalProperties: false
    OrderRoutingSuccessResponse:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/OrderRouting'
      additionalProperties: false
    OrderRoutingUpdate:
      type: object
      properties:
        operationCode:
          type:
          - string
          - 'null'
        employeeCode:
          type:
          - string
          - 'null'
        estimatedEndDate:
          type:
          - string
          - 'null'
          format: date-time
        estimatedStartDate:
          type:
          - string
          - 'null'
          format: date-time
        workCenter:
          type:
          - string
          - 'null'
      additionalProperties: false
    OrderRoutingCreate:
      required:
      - workCenterOrVendor
      type: object
      properties:
        certificationRequired:
          type: boolean
        cyclePrice:
          type:
          - number
          - 'null'
          format: double
        cycleTime:
          type:
          - number
          - 'null'
          format: double
        cycleUnit:
          type:
          - string
          - 'null'
        departmentNumber:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        employeeCode:
          type:
          - string
          - 'null'
        estimatedEndDate:
          type:
          - string
          - 'null'
          format: date-time
        estimatedQuantity:
          type:
          - integer
          - 'null'
          format: int32
        estimatedStartDate:
          type:
          - string
          - 'null'
          format: date-time
        ignoreVendorMinimum:
          type: boolean
        operationCode:
          type:
          - string
          - 'null'
        overlapSteps:
          type: boolean
        setupPrice:
          type:
          - number
          - 'null'
          format: double
        setupTime:
          type:
          - number
          - 'null'
          format: double
        shift2DefaultEmployeeCode:
          type:
          - string
          - 'null'
        shift3DefaultEmployeeCode:
          type:
          - string
          - 'null'
        stepNumber:
          type:
          - integer
          - 'null'
          format: int32
        timeUnit:
          type:
          - string
          - 'null'
        total:
          type:
          - number
          - 'null'
          format: double
        vendorCode:
          type:
          - string
          - 'null'
        workCenter:
          type:
          - string
          - 'null'
        workCenterOrVendor:
          type: string
      additionalProperties: false
    OrderRouting:
      type: object
      properties:
        actualEndDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        actualPiecesGood:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        actualPiecesScrap:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        actualStartDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        burdenRate:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        certificationRequired:
          type: boolean
          readOnly: true
        cost1:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost2:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost3:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost4:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost5:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost6:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost7:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cost8:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cyclePrice:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cycleRate:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cycleTime:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        cycleUnit:
          type:
          - string
          - 'null'
          readOnly: true
        departmentNumber:
          type:
          - string
          - 'null'
          readOnly: true
        description:
          type:
          - string
          - 'null'
          readOnly: true
        employeeCode:
          type:
          - string
          - 'null'
          readOnly: true
        estimatedEndDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        estimatedQuantity:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        estimatedStartDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        GLCode:
          type:
          - string
          - 'null'
          readOnly: true
        ignoreVendorMinimum:
          type: boolean
          readOnly: true
        itemNumber:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        jobClosedDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        jobStatus:
          type:
          - string
          - 'null'
          readOnly: true
        jobNumber:
          type:
          - string
          - 'null'
          readOnly: true
        laborAccount:
          type:
          - string
          - 'null'
          readOnly: true
        laborRate:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        lastModDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        lastModUser:
          type:
          - string
          - 'null'
          readOnly: true
        leadTime:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        machinesRun:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        markupPercent:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        numberMachinesForJob:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        operationCode:
          type:
          - string
          - 'null'
          readOnly: true
        orderNumber:
          type:
          - string
          - 'null'
          readOnly: true
        overlapSteps:
          type: boolean
          readOnly: true
        partNumber:
          type:
          - string
          - 'null'
          readOnly: true
        percentEfficient:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        scrapPercent:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup1:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup2:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup3:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup4:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup5:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup6:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup7:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setup8:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setupPrice:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setupRate:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        setupTime:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        shift2DefaultEmployeeCode:
          type:
          - string
          - 'null'
          readOnly: true
        shift3DefaultEmployeeCode:
          type:
          - string
          - 'null'
          readOnly: true
        status:
          type:
          - string
          - 'null'
          readOnly: true
        stepNumber:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        teamSize:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        tempEstimatedEndDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        tempEstimatedStartDate:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        timeUnit:
          type:
          - string
          - 'null'
          readOnly: true
        total:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        totalActualHours:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        totalEstimatedHours:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        totalHoursLeft:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        unattendedOperation:
          type: boolean
          readOnly: true
        uniqueID:
          type: integer
          format: int32
          readOnly: true
        unit1:
          type:
          - string
          - 'null'
          readOnly: true
        unit2:
          type:
          - string
          - 'null'
          readOnly: true
        unit3:
          type:
          - string
          - 'null'
          readOnly: true
        unit4:
          type:
          - string
          - 'null'
          readOnly: true
        unit5:
          type:
          - string
          - 'null'
          readOnly: true
        unit6:
          type:
          - string
          - 'null'
          readOnly: true
        unit7:
          type:
          - string
          - 'null'
          readOnly: true
        unit8:
          type:
          - string
          - 'null'
          readOnly: true
        vendorCode:
          type:
          - string
          - 'null'
          readOnly: true
        workCenter:
          type:
          - string
          - 'null'
          readOnly: true
        workCenterOrVendor:
          type:
          - string
          - 'null'
          readOnly: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: oauth2
      description: OAuth 2.0 Client Credentials Flow with API Users issued from Integration Engine Management Console
      flows:
        clientCredentials:
          tokenUrl: https://api-user.integrations.ecimanufacturing.com/oauth2/api-user/token
          scopes:
            openid: openid
